// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc8JYL_1oDq3AB9XRJYxyvHQs9vTRXILE',
    appId: '1:1093783214005:web:58c27903f8e0b3b184abfc',
    messagingSenderId: '1093783214005',
    projectId: 'todolistcoba',
    authDomain: 'todolistcoba.firebaseapp.com',
    storageBucket: 'todolistcoba.appspot.com',
    measurementId: 'G-E2SV3FQGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8dwvSjX8f1mU7Ek0hsvTwNjwv4qmBrNE',
    appId: '1:1093783214005:android:bd6ad997f161a5a384abfc',
    messagingSenderId: '1093783214005',
    projectId: 'todolistcoba',
    storageBucket: 'todolistcoba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQo2SmsyfdZVkSdHM6-B_d0lfgn79HTQA',
    appId: '1:1093783214005:ios:d61e7c8d39bc7d4484abfc',
    messagingSenderId: '1093783214005',
    projectId: 'todolistcoba',
    storageBucket: 'todolistcoba.appspot.com',
    iosBundleId: 'com.example.todoList2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQo2SmsyfdZVkSdHM6-B_d0lfgn79HTQA',
    appId: '1:1093783214005:ios:0d24068337ae58b584abfc',
    messagingSenderId: '1093783214005',
    projectId: 'todolistcoba',
    storageBucket: 'todolistcoba.appspot.com',
    iosBundleId: 'com.example.todoList2.RunnerTests',
  );
}
